# Generated by Django 4.0.3 on 2022-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sId', models.CharField(max_length=30)),
                ('sName', models.CharField(max_length=22)),
                ('sEmail', models.EmailField(max_length=254)),
                ('sGender', models.CharField(max_length=10)),
            ],
        ),
    ]
